/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FortuneTeller;

import java.text.DecimalFormat;

/**
 *
 * @author Milu
 */
public class CGPACalculation extends javax.swing.JFrame {

    /**
     * Creates new form CGPACalculation
     */
    public CGPACalculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "CSE", "EEE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th", "11th", "12th", " " }));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Subjects in selected department and");

        jTextField1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" Quiz Average");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(" Mid-term");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(" Final");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" Assignment");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText(" Presentation");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText(" Attendance");

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField8.setText("0");

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField9.setText("0");

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField10.setText("0");

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField11.setText("0");

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField12.setText("0");

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField13.setText("0");

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField14.setText("0");

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField15.setText("0");

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField16.setText("0");

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField17.setText("0");

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField18.setText("0");

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField19.setText("0");

        jTextField39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField39.setText("0");

        jTextField40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField40.setText("0");

        jTextField41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField41.setText("0");

        jTextField42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField42.setText("0");

        jTextField43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField43.setText("0");

        jTextField44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField44.setText("0");

        jTextField45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField45.setText("0");

        jTextField46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField46.setText("0");

        jTextField47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField47.setText("0");

        jTextField48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField48.setText("0");

        jTextField49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField49.setText("0");

        jTextField50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField50.setText("0");

        jTextField51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField51.setText("0");

        jTextField52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField52.setText("0");

        jTextField53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField53.setText("0");

        jTextField54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField54.setText("0");

        jTextField55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField55.setText("0");

        jTextField56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField56.setText("0");

        jTextField57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField57.setText("0");

        jTextField58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField58.setText("0");

        jTextField59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField59.setText("0");

        jTextField60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField60.setText("0");

        jTextField61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField61.setText("0");

        jTextField62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField62.setText("0");

        jTextField63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField63.setText("0");

        jTextField64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField64.setText("0");

        jTextField65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField65.setText("0");

        jTextField66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField66.setText("0");

        jTextField67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField67.setText("0");

        jTextField68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField68.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText(" Total");

        jTextField69.setBackground(new java.awt.Color(0, 0, 0));
        jTextField69.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField69.setForeground(new java.awt.Color(255, 255, 255));

        jTextField70.setBackground(new java.awt.Color(0, 0, 0));
        jTextField70.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField70.setForeground(new java.awt.Color(255, 255, 255));

        jTextField71.setBackground(new java.awt.Color(0, 0, 0));
        jTextField71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField71.setForeground(new java.awt.Color(255, 255, 255));

        jTextField72.setBackground(new java.awt.Color(0, 0, 0));
        jTextField72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField72.setForeground(new java.awt.Color(255, 255, 255));

        jTextField73.setBackground(new java.awt.Color(0, 0, 0));
        jTextField73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField73.setForeground(new java.awt.Color(255, 255, 255));

        jTextField74.setBackground(new java.awt.Color(0, 0, 0));
        jTextField74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField74.setForeground(new java.awt.Color(255, 255, 255));

        jTextField75.setBackground(new java.awt.Color(0, 0, 0));
        jTextField75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField75.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 0));
        jLabel16.setText(" GPA");

        jTextField78.setBackground(new java.awt.Color(0, 0, 0));
        jTextField78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField78.setForeground(new java.awt.Color(255, 255, 102));

        jTextField79.setBackground(new java.awt.Color(0, 0, 0));
        jTextField79.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField79.setForeground(new java.awt.Color(255, 255, 102));

        jTextField80.setBackground(new java.awt.Color(0, 0, 0));
        jTextField80.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField80.setForeground(new java.awt.Color(255, 255, 102));

        jTextField81.setBackground(new java.awt.Color(0, 0, 0));
        jTextField81.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField81.setForeground(new java.awt.Color(255, 255, 102));

        jTextField82.setBackground(new java.awt.Color(0, 0, 0));
        jTextField82.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField82.setForeground(new java.awt.Color(255, 255, 102));

        jTextField83.setBackground(new java.awt.Color(0, 0, 0));
        jTextField83.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField83.setForeground(new java.awt.Color(255, 255, 102));

        jTextField84.setBackground(new java.awt.Color(0, 0, 0));
        jTextField84.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField84.setForeground(new java.awt.Color(255, 255, 102));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("semester");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText(" Credit hours");

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField20.setText("0");

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField21.setText("0");

        jTextField85.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField85.setText("0");

        jTextField86.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField86.setText("0");

        jTextField87.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField87.setText("0");

        jTextField88.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField88.setText("0");

        jTextField89.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField89.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField89, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField63)
                            .addComponent(jTextField39)
                            .addComponent(jTextField14)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jTextField8)
                            .addComponent(jTextField45)
                            .addComponent(jTextField51)
                            .addComponent(jTextField57))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField64)
                            .addComponent(jTextField58)
                            .addComponent(jTextField52)
                            .addComponent(jTextField40)
                            .addComponent(jTextField15)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jTextField46)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField65, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jTextField59)
                                    .addComponent(jTextField53)
                                    .addComponent(jTextField47)
                                    .addComponent(jTextField41)
                                    .addComponent(jTextField10)
                                    .addComponent(jTextField16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField66, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTextField60, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField54, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField48, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField42, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField67)
                            .addComponent(jTextField61)
                            .addComponent(jTextField55)
                            .addComponent(jTextField43)
                            .addComponent(jTextField18)
                            .addComponent(jTextField12)
                            .addComponent(jTextField49)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField68, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField50, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField44, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField56, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField74, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField73, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField72, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField71, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField70, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField69, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField83, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField82, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField81, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField80, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField79, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField78, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9)
                    .addComponent(jTextField10)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12)
                    .addComponent(jTextField13)
                    .addComponent(jTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField65, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Calculate Total Marks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Calculate SGPA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Milu\\Documents\\NetBeansProjects\\Waiversystem\\Waiver calc cover.png")); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Calculate C.G.P.A");

        jLabel24.setText("@Meaningless_Compiler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField69.setEditable(false);
        jTextField70.setEditable(false);
        jTextField71.setEditable(false);
        jTextField72.setEditable(false);
        jTextField73.setEditable(false);
        jTextField74.setEditable(false);
        jTextField75.setEditable(false);
        jTextField78.setEditable(false);
        jTextField79.setEditable(false);
        jTextField80.setEditable(false);
        jTextField81.setEditable(false);
        jTextField82.setEditable(false);
        jTextField83.setEditable(false);
        jTextField84.setEditable(false);
        jTextField20.setEditable(false);
        jTextField21.setEditable(false);
        jTextField85.setEditable(false);
        jTextField86.setEditable(false);
        jTextField87.setEditable(false);
        jTextField88.setEditable(false);
        jTextField89.setEditable(false);
        if(jComboBox1.getSelectedItem().equals("CSE") && jComboBox2.getSelectedItem().equals("1st")){
            jTextField1.setText("History Of Bangladesh and Bangla Language");
            jTextField2.setText("Basic Physics Lab");
            jTextField3.setText("Basic Physics");
            jTextField4.setText("Computer Fundamentals");
            jTextField5.setText("Basic Functional English and English Spoken");
            jTextField6.setText("Basic Mathematics");
            jTextField7.setText("");
            jTextField20.setText("3");
            jTextField21.setText("1");
            jTextField85.setText("3");
            jTextField86.setText("3");
            jTextField87.setText("3");
            jTextField88.setText("3");
            jTextField89.setText("0");
            
        }
        
        else if(jComboBox1.getSelectedItem().equals("CSE") && jComboBox2.getSelectedItem().equals("4th")){
            jTextField1.setText("Object Oriented Programming");
            jTextField2.setText("Object Oriented Programming Lab");
            jTextField3.setText("Basic Electronics");
            jTextField4.setText("Basic Electronics Lab");
            jTextField5.setText("Engineering Mathematics");
            jTextField6.setText("Financial & Managerial Accounting");
            jTextField7.setText("Software Project II");
            jTextField20.setText("2");
            jTextField21.setText("2");
            jTextField85.setText("1");
            jTextField86.setText("2");
            jTextField87.setText("3");
            jTextField88.setText("2");
            jTextField89.setText("1");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String qavg1 = jTextField8.getText();
        String mid1 = jTextField9.getText();
        String fin1 = jTextField10.getText();
        String ass1 = jTextField11.getText();
        String pre1 = jTextField12.getText();
        String att1 = jTextField13.getText();
        int qavg_1 = Integer.parseInt(qavg1);
        int mid_1 = Integer.parseInt(mid1);
        int fin_1 = Integer.parseInt(fin1);
        int ass_1 = Integer.parseInt(ass1);
        int pre_1 = Integer.parseInt(pre1);
        int att_1 = Integer.parseInt(att1);
        int total1 = qavg_1 + mid_1 + fin_1 + ass_1 + pre_1 + att_1;
        String dis1 = String.valueOf(total1);
        jTextField69.setText(dis1);
        
        String qavg2 = jTextField14.getText();
        String mid2 = jTextField15.getText();
        String fin2 = jTextField16.getText();
        String ass2 = jTextField17.getText();
        String pre2 = jTextField18.getText();
        String att2 = jTextField19.getText();
        int qavg_2 = Integer.parseInt(qavg2);
        int mid_2 = Integer.parseInt(mid2);
        int fin_2 = Integer.parseInt(fin2);
        int ass_2 = Integer.parseInt(ass2);
        int pre_2 = Integer.parseInt(pre2);
        int att_2 = Integer.parseInt(att2);
        int total2 = qavg_2 + mid_2 + fin_2 + ass_2 + pre_2 + att_2;
        String dis2 = String.valueOf(total2);
        jTextField70.setText(dis2);
        
        String qavg3 = jTextField39.getText();
        String mid3 = jTextField40.getText();
        String fin3 = jTextField41.getText();
        String ass3 = jTextField42.getText();
        String pre3 = jTextField43.getText();
        String att3 = jTextField44.getText();
        int qavg_3 = Integer.parseInt(qavg3);
        int mid_3 = Integer.parseInt(mid3);
        int fin_3 = Integer.parseInt(fin3);
        int ass_3 = Integer.parseInt(ass3);
        int pre_3 = Integer.parseInt(pre3);
        int att_3 = Integer.parseInt(att3);
        int total3 = qavg_3 + mid_3 + fin_3 + ass_3 + pre_3 + att_3;
        String dis3 = String.valueOf(total3);
        jTextField71.setText(dis3);
        
        String qavg4 = jTextField45.getText();
        String mid4 = jTextField46.getText();
        String fin4 = jTextField47.getText();
        String ass4 = jTextField48.getText();
        String pre4 = jTextField49.getText();
        String att4 = jTextField50.getText();
        int qavg_4 = Integer.parseInt(qavg4);
        int mid_4 = Integer.parseInt(mid4);
        int fin_4 = Integer.parseInt(fin4);
        int ass_4 = Integer.parseInt(ass4);
        int pre_4 = Integer.parseInt(pre4);
        int att_4 = Integer.parseInt(att4);
        int total4 = qavg_4 + mid_4 + fin_4 + ass_4 + pre_4 + att_4;
        String dis4 = String.valueOf(total4);
        jTextField72.setText(dis4);
        
        String qavg5 = jTextField51.getText();
        String mid5 = jTextField52.getText();
        String fin5 = jTextField53.getText();
        String ass5 = jTextField54.getText();
        String pre5 = jTextField55.getText();
        String att5 = jTextField56.getText();
        int qavg_5 = Integer.parseInt(qavg5);
        int mid_5 = Integer.parseInt(mid5);
        int fin_5 = Integer.parseInt(fin5);
        int ass_5 = Integer.parseInt(ass5);
        int pre_5 = Integer.parseInt(pre5);
        int att_5 = Integer.parseInt(att5);
        int total5 = qavg_5 + mid_5 + fin_5 + ass_5 + pre_5 + att_5;
        String dis5 = String.valueOf(total5);
        jTextField73.setText(dis5);
        
        String qavg6 = jTextField57.getText();
        String mid6 = jTextField58.getText();
        String fin6 = jTextField59.getText();
        String ass6 = jTextField60.getText();
        String pre6 = jTextField61.getText();
        String att6 = jTextField62.getText();
        int qavg_6 = Integer.parseInt(qavg6);
        int mid_6 = Integer.parseInt(mid6);
        int fin_6 = Integer.parseInt(fin6);
        int ass_6 = Integer.parseInt(ass6);
        int pre_6 = Integer.parseInt(pre6);
        int att_6 = Integer.parseInt(att6);
        int total6 = qavg_6 + mid_6 + fin_6 + ass_6 + pre_6 + att_6;
        String dis6 = String.valueOf(total6);
        jTextField74.setText(dis6);
        
        String qavg7 = jTextField63.getText();
        String mid7 = jTextField64.getText();
        String fin7 = jTextField65.getText();
        String ass7 = jTextField66.getText();
        String pre7 = jTextField67.getText();
        String att7 = jTextField68.getText();
        int qavg_7 = Integer.parseInt(qavg7);
        int mid_7 = Integer.parseInt(mid7);
        int fin_7 = Integer.parseInt(fin7);
        int ass_7 = Integer.parseInt(ass7);
        int pre_7 = Integer.parseInt(pre7);
        int att_7 = Integer.parseInt(att7);
        int total7 = qavg_7 + mid_7 + fin_7 + ass_7 + pre_7 + att_7;
        String dis7 = String.valueOf(total7);
        jTextField75.setText(dis7);
        
        if(total1 <40){
            jTextField78.setText("0.00");
        }
        else if(total1>=40 && total1 <= 44){
            jTextField78.setText("2.00");
        }
        else if(total1>=45 && total1 <= 49){
            jTextField78.setText("2.25");
        }
        else if(total1>=50 && total1 <= 54){
            jTextField78.setText("2.50");
        }
        else if(total1>=55 && total1 <= 59){
            jTextField78.setText("2.75");
        }
        else if(total1>=60 && total1 <= 64){
            jTextField78.setText("3.00");
        }
        else if(total1>=65 && total1 <= 69){
            jTextField78.setText("3.25");
        }
        else if(total1>=70 && total1 <= 74){
            jTextField78.setText("3.50");
        }
        else if(total1>=75 && total1 <= 79){
            jTextField78.setText("3.75");
        }
        else if(total1>=80 && total1 <= 100){
            jTextField78.setText("4.00");
        }
        
        
        if(total2 <40){
            jTextField79.setText("0.00");
        }
        else if(total2>=40 && total2 <= 44){
            jTextField79.setText("2.00");
        }
        else if(total2>=45 && total2 <= 49){
            jTextField79.setText("2.25");
        }
        else if(total2>=50 && total2 <= 54){
            jTextField79.setText("2.50");
        }
        else if(total2>=55 && total2 <= 59){
            jTextField79.setText("2.75");
        }
        else if(total2>=60 && total2 <= 64){
            jTextField79.setText("3.00");
        }
        else if(total2>=65 && total2 <= 69){
            jTextField79.setText("3.25");
        }
        else if(total2>=70 && total2 <= 74){
            jTextField79.setText("3.50");
        }
        else if(total2>=75 && total2 <= 79){
            jTextField79.setText("3.75");
        }
        else if(total2>=80 && total2 <= 100){
            jTextField79.setText("4.00");
        }
        
        if(total3 <40){
            jTextField80.setText("0.00");
        }
        else if(total3>=40 && total3 <= 44){
            jTextField80.setText("2.00");
        }
        else if(total3>=45 && total3 <= 49){
            jTextField80.setText("2.25");
        }
        else if(total3>=50 && total3 <= 54){
            jTextField80.setText("2.50");
        }
        else if(total3>=55 && total3 <= 59){
            jTextField80.setText("2.75");
        }
        else if(total3>=60 && total3 <= 64){
            jTextField80.setText("3.00");
        }
        else if(total3>=65 && total3 <= 69){
            jTextField80.setText("3.25");
        }
        else if(total3>=70 && total3 <= 74){
            jTextField80.setText("3.50");
        }
        else if(total3>=75 && total3 <= 79){
            jTextField80.setText("3.75");
        }
        else if(total3>=80 && total3 <= 100){
            jTextField80.setText("4.00");
        }
        
        if(total4 <40){
            jTextField81.setText("0.00");
        }
        else if(total4>=40 && total4 <= 44){
            jTextField81.setText("2.00");
        }
        else if(total4>=45 && total4 <= 49){
            jTextField81.setText("2.25");
        }
        else if(total4>=50 && total4 <= 54){
            jTextField81.setText("2.50");
        }
        else if(total4>=55 && total4 <= 59){
            jTextField81.setText("2.75");
        }
        else if(total4>=60 && total4 <= 64){
            jTextField81.setText("3.00");
        }
        else if(total4>=65 && total4 <= 69){
            jTextField81.setText("3.25");
        }
        else if(total4>=70 && total4 <= 74){
            jTextField81.setText("3.50");
        }
        else if(total4>=75 && total4 <= 79){
            jTextField81.setText("3.75");
        }
        else if(total4>=80 && total4 <= 100){
            jTextField81.setText("4.00");
        }
        
        if(total5 <40){
            jTextField82.setText("0.00");
        }
        else if(total5>=40 && total5 <= 44){
            jTextField82.setText("2.00");
        }
        else if(total5>=45 && total5 <= 49){
            jTextField82.setText("2.25");
        }
        else if(total5>=50 && total5 <= 54){
            jTextField82.setText("2.50");
        }
        else if(total5>=55 && total5 <= 59){
            jTextField82.setText("2.75");
        }
        else if(total5>=60 && total5 <= 64){
            jTextField82.setText("3.00");
        }
        else if(total5>=65 && total5 <= 69){
            jTextField82.setText("3.25");
        }
        else if(total5>=70 && total5 <= 74){
            jTextField82.setText("3.50");
        }
        else if(total5>=75 && total5 <= 79){
            jTextField82.setText("3.75");
        }
        else if(total5>=80 && total5 <= 100){
            jTextField82.setText("4.00");
        }
        
        if(total6 <40){
            jTextField83.setText("0.00");
        }
        else if(total6>=40 && total6 <= 44){
            jTextField83.setText("2.00");
        }
        else if(total6>=45 && total6 <= 49){
            jTextField83.setText("2.25");
        }
        else if(total6>=50 && total6 <= 54){
            jTextField83.setText("2.50");
        }
        else if(total6>=55 && total6 <= 59){
            jTextField83.setText("2.75");
        }
        else if(total6>=60 && total6 <= 64){
            jTextField83.setText("3.00");
        }
        else if(total6>=65 && total6 <= 69){
            jTextField83.setText("3.25");
        }
        else if(total6>=70 && total6 <= 74){
            jTextField83.setText("3.50");
        }
        else if(total6>=75 && total6 <= 79){
            jTextField83.setText("3.75");
        }
        else if(total6>=80 && total6 <= 100){
            jTextField83.setText("4.00");
        }
        
        if(total7 <40){
            jTextField84.setText("0.00");
        }
        else if(total7>=40 && total7 <= 44){
            jTextField84.setText("2.00");
        }
        else if(total7>=45 && total7 <= 49){
            jTextField84.setText("2.25");
        }
        else if(total7>=50 && total7 <= 54){
            jTextField84.setText("2.50");
        }
        else if(total7>=55 && total7 <= 59){
            jTextField84.setText("2.75");
        }
        else if(total7>=60 && total7 <= 64){
            jTextField84.setText("3.00");
        }
        else if(total7>=65 && total7 <= 69){
            jTextField84.setText("3.25");
        }
        else if(total7>=70 && total7 <= 74){
            jTextField84.setText("3.50");
        }
        else if(total7>=75 && total7 <= 79){
            jTextField84.setText("3.75");
        }
        else if(total7>=80 && total7 <= 100){
            jTextField84.setText("4.00");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String cg1 = jTextField78.getText();
        String cg2 = jTextField79.getText();
        String cg3 = jTextField80.getText();
        String cg4 = jTextField81.getText();
        String cg5 = jTextField82.getText();
        String cg6 = jTextField83.getText();
        String cg7 = jTextField84.getText();
        String ch1 = jTextField20.getText();
        String ch2 = jTextField21.getText();
        String ch3 = jTextField85.getText();
        String ch4 = jTextField86.getText();
        String ch5 = jTextField87.getText();
        String ch6 = jTextField88.getText();
        String ch7 = jTextField89.getText();
        
        double cg_1 = Double.parseDouble(cg1);
        double cg_2 = Double.parseDouble(cg2);
        double cg_3 = Double.parseDouble(cg3);
        double cg_4 = Double.parseDouble(cg4);
        double cg_5 = Double.parseDouble(cg5);
        double cg_6 = Double.parseDouble(cg6);
        double cg_7 = Double.parseDouble(cg7);
        double ch_1 = Double.parseDouble(ch1);
        double ch_2 = Double.parseDouble(ch2);
        double ch_3 = Double.parseDouble(ch3);
        double ch_4 = Double.parseDouble(ch4);
        double ch_5 = Double.parseDouble(ch5);
        double ch_6 = Double.parseDouble(ch6);
        double ch_7 = Double.parseDouble(ch7);
        double total_credit = ch_1+ch_2+ch_3+ch_4+ch_5+ch_6+ch_7;
        double total_sgpa = ((cg_1*ch_1) + (cg_2*ch_2) + (cg_3*ch_3) + (cg_4*ch_4) + (cg_5*ch_5) + (cg_6*ch_6) + (cg_7*ch_7))/total_credit;
        double value = Double.parseDouble(new DecimalFormat("##.##").format(total_sgpa));
        String dis_sgpa = String.valueOf(value);
        
        if(value < 2){
            jTextField77.setText("You are Failed");
        }
        else if(value >= 2 && value <= 2.24){
            jTextField77.setText("Grade = D");
        }
        else if(value >= 2.25 && value <=2.49){
            jTextField77.setText("Grade = C");
        }
        else if(value >= 2.50 && value <=2.74){
            jTextField77.setText("Grade = C+");
        }
        else if(value >= 2.75 && value <=2.99){
            jTextField77.setText("Grade = B-");
        }
        else if(value >= 3.00 && value <= 3.24){
            jTextField77.setText("Grade = B");
        }
        else if(value >= 3.25 && value <= 3.49){
            jTextField77.setText("Grade = B+");
        }
        else if(value >= 3.50 && value <= 3.74){
            jTextField77.setText("Grade = A-");
        }
        else if(value >= 3.75 && value <= 3.99){
            jTextField77.setText("Grade = A");
        }
        else if(value == 4.00){
            jTextField77.setText("Grade = A+");
        }
        
        jTextField76.setText("S.G.P.A: "+dis_sgpa);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Startpage().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CGPACalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CGPACalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CGPACalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CGPACalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CGPACalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
